### ISSUE TITLE
What is difficulty weight and difficulty, and how is it calculated?

### ISSUE THREAD

**Issue by yashdeshpande** [skribbliohints/skribbliohints.github.io#2]

**Comment by skribbliohints** [comment]
difficulty is 1 - (number of players that guess correctly / total number of players).  difficultyWeight is the total number of players used to calculate the difficulty.  It would make sense if difficultyWeight was no more than 8 times the publicGameCount.  But there is something wrong with the difficultyWeight values, since in some cases it is more than 100 times the publicGameCount.  The bot code looks like it updates the difficulty if `$("div.content:nth-child(1) > div:nth-child(1)")[0].innerHTML` begins with "The word was: " and at least 10 seconds have passed since it last updated the difficulty.  It gets the number of players who have guessed correctly from `$(".guessedWord").length`.  It gets the number of players from `document.getElementById("containerGamePlayers").children.length`.

**Comment by skribbliohints** [comment]
I think that the error is in publicGameCount.  I think the bot only incremented publicGameCount if the bot guessed the word.  If the bot didn't guess the word, it updated difficulty and difficultyWeight, but not publicGameCount.
