### ISSUE TITLE
King kong is missing

### ISSUE THREAD

**Issue by edisionnano** [skribbliohints/skribbliohints.github.io#5]
The word king kong is missing

**Comment by skribbliohints** [comment]
The word King Kong is in the data for all 3 languages (English, German, and Spanish).
![kingKong](https://user-images.githubusercontent.com/56850561/160215678-38896084-bc44-472a-9e16-b90cf7b244d3.png)
![kingKongGerman](https://user-images.githubusercontent.com/56850561/160216027-0372e581-be56-45c0-864b-f792463c6b57.png)
![kingKongSpanish](https://user-images.githubusercontent.com/56850561/160216056-fb1dc338-d68e-4c56-8a07-57551dc62fb2.png)
Maybe you typed something like 'k___ ____' and it did not appear because it is case-sensitive.
