### ISSUE TITLE
"AC/DC" doesn't show up in hints for "_____"

### ISSUE THREAD

**Issue by ghost** [skribbliohints/skribbliohints.github.io#7]

**Comment by skribbliohints** [comment]
Hello,
My memory may be faulty here, but I thought skribbl.io used the hint `__/__` for AC/DC.  It is possible that the recent update changed the hints so now it uses `_____` for AC/DC.
In any case, I should change the JavaScript code to include AC/DC for `_____` because it sounds like users expect AC/DC to be included for that hint.
Right now the word data in the JSON files is critically outdated.  It is more valuable to get an updated word list than to fix this searching behavior, so I might put this issue off and work on getting an updated word list instead.  But I do plan to do something about this issue.

**Comment by ghost** [comment]
It sometimes uses the hint `__/__`, but you have to wait until the `/` shows up because it is treated as a letter. Even in the old skribbl.io, it always initially used `_____` before any letters showed up.

Maybe you should make the bot record the initial hint when collecting the new word list, just in case one of these edge cases occur?

**Comment by skribbliohints** [comment]
Based on what @46009361 is saying, / is treated as a letter but - is not.
So I am fixing this issue by making a one-character change to treat / as a letter.
This affects only one word, AC/DC.
